import React from 'react';
import PropTypes from 'prop-types';
import { Button } from '../ui/button.jsx';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card.jsx';
import { Skeleton } from '../ui/skeleton.jsx';
import { Sparkle, Info, RefreshCw, MessageSquare, AlertCircle, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

/**
 * PortfolioSummary component displays an AI-generated portfolio summary.
 * It includes loading states, an explanation tooltip, and action buttons for regeneration/feedback.
 *
 * @param {object} props - Component props.
 * @param {string} props.summary - The AI-generated portfolio summary text.
 * @param {boolean} props.isLoading - Indicates if the summary is currently being generated.
 * @param {function} props.onRegenerate - Callback function to trigger AI summary regeneration.
 */
export function PortfolioSummary({ summary, isLoading, onRegenerate }) {
  return (
    <Card className="p-6 shadow-md rounded-lg bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700">
      <CardHeader className="p-0 pb-2">
        <CardTitle className="text-2xl font-bold text-gray-900 dark:text-gray-50 flex items-center gap-2">
          <Sparkle className="h-6 w-6 text-pink-500" /> AI-Generated Summary
          <Info
            className="h-4 w-4 text-gray-400 ml-2 cursor-pointer"
            title="This summary is generated by AI based on your profile bio, skills, and project descriptions."
            aria-label="Information about AI-generated portfolio summary"
          />
        </CardTitle>
      </CardHeader>
      <CardContent className="p-0 text-gray-700 dark:text-gray-300 leading-relaxed">
        {isLoading ? (
          <div className="space-y-2">
            <Skeleton className="h-4 w-full rounded-md" />
            <Skeleton className="h-4 w-5/6 rounded-md" />
          </div>
        ) : summary ? (
          <p>{summary}</p>
        ) : (
          <p className="text-gray-500 dark:text-gray-400 text-sm">No summary available. Fill in your portfolio, skills, and bio to generate an AI-powered project summary!</p>
        )}
        <div className="flex justify-end mt-4 gap-2">
          <Button
            variant="ghost"
            size="sm"
            className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500"
            onClick={onRegenerate}
            disabled={isLoading}
            aria-label="Regenerate AI portfolio summary"
          >
            {isLoading ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <RefreshCw className="h-4 w-4 mr-1" />} Regenerate
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="text-gray-500 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-500"
            onClick={() => toast.info('Feedback feature coming soon!')}
            aria-label="Give feedback on AI summary"
          >
            <MessageSquare className="h-4 w-4 mr-1" /> Feedback
          </Button>
        </div>
        <p className="text-xs text-gray-400 dark:text-gray-600 mt-2">
          <AlertCircle className="inline h-3 w-3 mr-1" aria-hidden="true" /> Powered by AI. Content may vary.
        </p>
      </CardContent>
    </Card>
  );
}

PortfolioSummary.propTypes = {
  summary: PropTypes.string,
  isLoading: PropTypes.bool.isRequired,
  onRegenerate: PropTypes.func.isRequired,
};
PortfolioSummary.defaultProps = {
  summary: '',
};
export default PortfolioSummary;
        